name: Build and Test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        go-version: [1.14, 1.15]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: [1.14, 1.15]

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic
      
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: true

  build:
    name: Build
    runs-on: ubuntu-latest 
    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: [1.14, 1.15]

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build for Raspberry OS architecture
        run: env GOOS=linux GOARCH=arm GOARM=5 go build -o rpi cmd/api/main.go